// personalfinances-svelte/src/Home.svelte
<script>
    import { onMount } from 'svelte';

    import Icon from 'fa-svelte';
    import { 
        faLandmark, 
        faReceipt, 
        faHandHoldingUsd, 
        faPiggyBank, 
        faPlus 
     } from '@fortawesome/free-solid-svg-icons';

    import Chart from 'chart';
    import Line from "svelte-chartjs/src/Line.svelte";

    import MiniCard from './MiniCard.svelte';
    import ButtonAddTransac from './ButtonAddTransac.svelte';
    import AddExpenseModal from './AddExpenseModal.svelte';
    import AddRevenueModal from './AddRevenueModal.svelte';

    import api from './services/api';

    import { groupTransactionsByDate } from './utils/TransactionsUtils';
    
    let classTransacOptionsVisible = '';
    let revenueSum = 0;
    let expenseSum = 0;
    let expenseModalVisible = false;
    let revenueModalVisible = false;

    let balance = 0;
    let currentMoney = 0;
    let expensesCurrentMonth = [];
    let revenuesCurrentMonth = [];
    let chartDataRevenue = {};
    let chartDataExpense = {};
    let loadedApiData = false;

    let commonChartOptions = {
        maintainAspectRatio: false,
        responsive: true,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }

    
    function setTransacOptionsVisible() {
        if (classTransacOptionsVisible === '' || classTransacOptionsVisible === 'hide') {
            classTransacOptionsVisible = 'show';
        } else {
            classTransacOptionsVisible = 'hide';
        }
    }

    function setExpenseModalVisible(isVisible) {
        expenseModalVisible = isVisible;
    }

    function setRevenueModalVisible(isVisible) {
        revenueModalVisible = isVisible;
    }


    function getTransactions() {
        loadedApiData = false;

        Promise
            .all([
                api.get("/metrics"), 
                api.get("/expenses/?currentMonth=true"),
                api.get("/revenues/?currentMonth=true")
            ])
            .then(results => {
                const metrics = results[0].data;

                balance = metrics.balance;
                currentMoney = metrics.currentMoney;
                expenseSum = metrics.expensesCurrentMonthSum;
                revenueSum = metrics.revenuesCurrentMonthSum;

                expensesCurrentMonth = groupTransactionsByDate(results[1].data);
                revenuesCurrentMonth = groupTransactionsByDate(results[2].data);

                chartDataRevenue = {
                        labels: revenuesCurrentMonth.map(revenue => revenue[0]),
                        datasets: [{
                            label: "Despesas por data",
                            fill: true,
                            data: revenuesCurrentMonth.map(revenue => revenue[1]),
                            borderColor: "rgb(50, 168, 82)",
                            backgroundColor: "rgb(50, 168, 82)"
                        }]
                }
                
                chartDataExpense = {
                        labels: expensesCurrentMonth.map(expense => expense[0]),
                        datasets: [{
                            label: "Despesas por data",
                            fill: true,
                            data: expensesCurrentMonth.map(expense => expense[1]),
                            borderColor: "rgb(255, 99, 132)",
                            backgroundColor: "rgb(255, 99, 132)"
                        }]
                }
            })
            .catch(function(error) {
                console.log(error)
                alert("Ops! Algo deu errado. Não foi possível recuperar as transações. Por favor tente novamente")
            });
    }

    
    onMount(getTransactions);
</script>


<div>
    <div class="row">
        <MiniCard title="Saldo Atual" value="{currentMoney}" type="balance" icon={faLandmark} />
        <MiniCard title="Receitas" value="{revenueSum}" type="revenue" icon={faHandHoldingUsd} />
        <MiniCard title="Despesas" value="{expenseSum}" type="expense" icon={faReceipt} />
        <MiniCard title="Balanço" value="{balance}" type="profit" icon={faPiggyBank} />
    </div>
    <div class="row">
        <div class="card">
            <label for="" class="card-title">Despesas do mês</label>
            <div>
                <Line 
                    data={chartDataExpense}
                    options={commonChartOptions}
                    height={400}
                />
            </div>
        </div>
        <div class="card">
            <label for="" class="card-title">Receitas do mês</label>
            <div>
                <Line 
                    data={chartDataRevenue}
                    options={commonChartOptions}
                    height={400}
                />
            </div>
        </div>
    </div>
    <button class="add-transaction" on:click={setTransacOptionsVisible}>
        <Icon icon={faPlus} />
    </button>
    <ButtonAddTransac
        classType="revenue" 
        classVisible="{classTransacOptionsVisible}" 
        icon={faReceipt} 
        onclickFunction={() => setRevenueModalVisible(true)} 
    />
    <ButtonAddTransac 
        classType="expense" 
        classVisible="{classTransacOptionsVisible}" 
        icon={faHandHoldingUsd} 
        onclickFunction={() => setExpenseModalVisible(true)}
    />
    <AddExpenseModal 
        isVisible={expenseModalVisible}
        setVisible={setExpenseModalVisible}
        addExpenseCallback={getTransactions}
    />
    <AddRevenueModal
        isVisible={revenueModalVisible}
        setVisible={setRevenueModalVisible}
        addRevenueCallback={getTransactions}
    />
</div>


<style>
    .card{
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
        flex: 1;
        margin: 10px;
        min-width: 45%;
        border-radius: 15px;
        background-color: #ffffff;
        padding: 10px;
    }
    .card .card-title {
        font-weight: bold;
        font-size: 14px;
    }
    .add-transaction {
        position: fixed;
        right: 10px;
        bottom: 30px;
        background-color: #2061bd;
        /* padding: 17px 18px; */
        border-radius: 50%;
        color: #FFF;
        font-size: 14px;
        cursor: pointer;
        width: 50px;
        height: 50px;
    }
    
</style>

// personalfinances-react/src/pages/Home/index.js
import React, { useState, useEffect } from 'react';

import { Line } from 'react-chartjs-2';

import { FaLandmark, FaHandHoldingUsd, FaReceipt, FaPiggyBank, FaPlus } from "react-icons/fa";

import './style.css';

import MiniCard from '../../components/MiniCard';
import ButtonAddTransac from '../../components/ButtonAddTransac';
import AddExpenseModal from '../../components/AddExpenseModal';
import AddRevenueModal from '../../components/AddRevenueModal';

import api from '../../services/api';

import { groupTransactionsByDate } from '../../utils/TransactionsUtils';

export default function Home() {
    
    const [addExpenseModalVisible, setAddExpenseModalVisible] = useState(false);
    const [addRevenueModalVisible, setAddRevenueModalVisible] = useState(false);
    const [classTransacOptionsVisible, setClassTransacOptionsVisible] = useState('');
    const [revenueSum, setRevenueSum] = useState(0);
    const [expenseSum, setExpenseSum] = useState(0);
    const [balance, setBalance] = useState(0);
    const [currentMoney, setCurrentMoney] = useState(0);
    const [expensesCurrentMonth, setExpenseCurrentMonth] = useState([]);
    const [revenuesCurrentMonth, setRevenuesCurrentMonth] = useState([]);
    const [expensesByDate, setExpensesByDate] = useState([]);
    const [revenuesByDate, setRevenuesByDate] = useState([]);

    function setTransacOptionsVisible() {
        if (classTransacOptionsVisible === '' || classTransacOptionsVisible === 'hide') {
            setClassTransacOptionsVisible('show');
        } else {
            setClassTransacOptionsVisible('hide');
        }
    }

    function getMetrics() {
        Promise
            .all([
                api.get("/metrics"), 
                api.get("/expenses/?currentMonth=true"),
                api.get("/revenues/?currentMonth=true")
            ])
            .then(function(results) {
                const metrics = results[0].data;
                setBalance(metrics.balance);
                setCurrentMoney(metrics.currentMoney);
                setExpenseSum(metrics.expensesCurrentMonthSum);
                setRevenueSum(metrics.revenuesCurrentMonthSum);
                setExpenseCurrentMonth(results[1].data);
                setRevenuesCurrentMonth(results[2].data);
            })
            .catch(function(error) {
                alert("Ops! Algo deu errado. Não foi possível recuperar as transações. Por favor tente novamente")
            });
    }

    useEffect(() => {
        getMetrics();
    }, []);

    useEffect(() => {
        let expensesByDateTemp = groupTransactionsByDate(expensesCurrentMonth);

        setExpensesByDate(expensesByDateTemp);
    }, [expensesCurrentMonth]);


    useEffect(() => {
        let revenuesByDateTemp = groupTransactionsByDate(revenuesCurrentMonth);

        setRevenuesByDate(revenuesByDateTemp);
    }, [revenuesCurrentMonth]);

    return (
        <div className="container">
            <div className="inner">
                <div className="row">
                    <MiniCard title="Saldo Atual" value={currentMoney} type="balance" icon={<FaLandmark color="#fff" size={18} />} />
                    <MiniCard title="Receitas" value={revenueSum} type="revenue" icon={<FaHandHoldingUsd color="#fff" size={24} />} />
                    <MiniCard title="Despesas" value={expenseSum} type="expense" icon={<FaReceipt color="#fff" size={18} />} />
                    <MiniCard title="Balanço" value={balance} type="profit" icon={<FaPiggyBank color="#fff" size={20} />} />
                </div>
                <div className="row">
                    <div className="card">
                        <label className="card-title">Despesas do mês</label>
                        <div>
                            <Line 
                                data={{
                                    options: {
                                        maintainAspectRatio: false,
                                        scales: {
                                            yAxes: [{
                                                ticks: {
                                                    beginAtZero: true
                                                }
                                            }]
                                        }
                                    },
                                    labels: expensesByDate.map((expense) => expense[0]),
                                    datasets: [{
                                        datasetKeyProvider: 'expenseCurrentMonthDataSet',
                                        label: 'Despesas por data',
                                        data: expensesByDate.map((expense) => expense[1]),
                                        fill: true,
                                        borderColor: "rgb(255, 99, 132)",
                                        backgroundColor: "rgb(255, 99, 132)"
                                    }]
                                }}
                            />
                        </div>
                    </div>
                    <div className="card">
                        <label className="card-title">Receitas do mês</label>
                        <div>
                            <Line 
                                data={{
                                    labels: revenuesByDate.map((revenue) => revenue[0]),
                                    datasets: [{
                                        datasetKeyProvider: 'revenueCurrentMonthDataSet',
                                        label: 'Receitas por data',
                                        data: revenuesByDate.map((revenue) => revenue[1]),
                                        fill: true,
                                        borderColor: "rgb(50, 168, 82)",
                                        backgroundColor: "rgb(50, 168, 82)"
                                    }],
                                    options: {
                                        maintainAspectRatio: false,
                                        scales: {
                                            yAxes: [{
                                                ticks: {
                                                    beginAtZero: true
                                                }
                                            }]
                                        }
                                    },
                                }}
                            />
                        </div>
                    </div>
                </div>

                <button className="add-transaction" onClick={setTransacOptionsVisible}>
                    <FaPlus color="#fff" size={18} />
                </button>

                <ButtonAddTransac 
                    classType="revenue" 
                    classVisible={classTransacOptionsVisible} 
                    onclick={() => setAddRevenueModalVisible(true)}
                    icon={<FaHandHoldingUsd color="#fff" size={19} />} 
                />
                <ButtonAddTransac 
                    classType="expense" 
                    classVisible={classTransacOptionsVisible} 
                    onclick={() => setAddExpenseModalVisible(true)}
                    icon={<FaReceipt color="#fff" size={16} />} 
                />
            </div>

            <AddExpenseModal 
                visible={addExpenseModalVisible} 
                setVisible={setAddExpenseModalVisible}
                addExpenseCallback={getMetrics}
            />
            <AddRevenueModal 
                visible={addRevenueModalVisible} 
                setVisible={setAddRevenueModalVisible} 
                addRevenueCallback={getMetrics}
            />
        </div>
    );
}
