// personalfinances-react/src/components/AddExpenseModal.js
import React, { useState } from 'react';


export default function AddExpenseModal({ visible, setVisible, addExpenseCallback }) {
    const [expenseTitle, setExpenseTitle] = useState("");
    const [expenseValue, setExpenseValue] = useState(0);
    
    function addExpense(event) {
        event.preventDefault();

        if (!expenseValue || expenseTitle.trim() === '') {
            alert("Todos os campos são obrigatórios");
            return;
        }

        if (expenseValue < 0) {
            alert("Valor da receita inválido");
            return;
        }

        setVisible(false);
        addExpenseCallback(expenseValue);
    }

    return (
        <div id="modalAddExpense" className="modal" style={{ display: (visible ? 'flex' : 'none') }}>
            <div className="modal-content expense">
                <div className="modal-header">
                    <h2>Adicionar Despesa</h2>
                    <span className="close" onClick={() => setVisible(false)}>&times;</span>
                </div>
                <form onSubmit={addExpense}>
                    <div className="modal-body">
                        <div className="form-group">
                            <p>Adicionar o titulo da despesa</p>
                            <input 
                                type="text" 
                                id="titleExpense" 
                                placeholder="Titulo..." 
                                value={expenseTitle}
                                onChange={(event) => setExpenseTitle(event.target.value)}
                            />
                        </div>
                        <div className="form-group">
                            <p>Adicione o valor da despesa</p>
                            <input 
                                type="number" 
                                id="valueExpense" 
                                placeholder="Valor..." 
                                onChange={(event) => setExpenseValue(parseFloat(event.target.value)) } 
                            />
                        </div>
                    </div>
                    <div className="modal-footer">
                        <button className="add" id="btnAddExpense">Adicionar</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

// personalfinances-angular/src/app/AddExpenseModal.component.ts
import {Component, Input, EventEmitter, Output} from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
    selector: 'add-expense-modal',
    templateUrl: './AddExpenseModal.component.html',
    styleUrls: ['./AddTransactionModal.component.css']
})
export class AddExpenseModal {
    @Input() isVisible: boolean;
    @Output() setVisible = new EventEmitter();
    @Output() addExpenseCallback = new EventEmitter();

    expenseForm = new FormGroup({
        title: new FormControl(''),
        value: new FormControl('')
    });

    close() {
        this.setVisible.emit(false);
    }

    addExpense() {
        if (this.expenseForm.value.title.trim() === '' || this.expenseForm.value.value === '') {
            alert("Todos os campos são obrigatórios");
            return;
        }

        if (this.expenseForm.value.value < 0) {
            alert("Valor da despesa inválido");
            return;
        }

        this.addExpenseCallback.emit(this.expenseForm.value.value);
        this.close();
        this.expenseForm.reset();
    }
}

<div id="modalAddExpense" class="modal" [ngClass]="{ show:isVisible }">
    <div class="modal-content expense">
        <div class="modal-header">
            <h2>Adicionar Despesa</h2>
            <span class="close" (click)="close()">&times;</span>
        </div>
        <form (ngSubmit)="addExpense()" [formGroup]="expenseForm">
            <div class="modal-body">
                <div class="form-group">
                    <p>Adicionar o titulo da despesa</p>
                    <input 
                        type="text" 
                        id="titleExpense" 
                        placeholder="Titulo..." 
                        formControlName="title"
                    />
                </div>
                <div class="form-group">
                    <p>Adicione o valor da despesa</p>
                    <input 
                        type="number" 
                        id="valueExpense" 
                        formControlName="value"
                    />
                </div>
            </div>
            <div class="modal-footer">
                <button class="add" id="btnAddExpense" type="submit">Adicionar</button>
            </div>
        </form>
    </div>
</div>
