// personalfinances-angular/src/app/AddRevenueModal.component.ts
import {Component, Input, EventEmitter, Output} from '@angular/core';
import { FormGroup, FormControl } from '@angular/forms';

@Component({
    selector: 'add-revenue-modal',
    templateUrl: './AddRevenueModal.component.html',
    styleUrls: ['./AddTransactionModal.component.css']
})
export class AddRevenueModal {
    @Input() isVisible: boolean;
    @Output() setVisible = new EventEmitter();
    @Output() addRevenueCallback = new EventEmitter();

    revenueForm = new FormGroup({
        title: new FormControl(''),
        value: new FormControl('')
    });

    close() {
        this.setVisible.emit(false);
    }

    addRevenue() {
        if (this.revenueForm.value.title.trim() === '' || this.revenueForm.value.value === '') {
            alert("Todos os campos são obrigatórios");
            return;
        }

        if (this.revenueForm.value.value < 0) {
            alert("Valor da receita inválido");
            return;
        }

        this.addRevenueCallback.emit(this.revenueForm.value.value);
        this.close();
        this.revenueForm.reset();
    }
}

<div id="modalAddRevenue" class="modal" [ngClass]="{ show:isVisible }">
    <div class="modal-content revenue">
        <div class="modal-header">
            <h2>Adicionar Despesa</h2>
            <span class="close" (click)="close()">&times;</span>
        </div>
        <form (ngSubmit)="addRevenue()" [formGroup]="revenueForm">
            <div class="modal-body">
                <div class="form-group">
                    <p>Adicionar o titulo da Receita</p>
                    <input 
                        type="text" 
                        id="titlerevenue" 
                        placeholder="Titulo..." 
                        formControlName="title"
                    />
                </div>
                <div class="form-group">
                    <p>Adicione o valor da receita</p>
                    <input 
                        type="number" 
                        id="valueRevenue" 
                        formControlName="value"
                    />
                </div>
            </div>
            <div class="modal-footer">
                <button class="add" id="btnAddRevenue" type="submit">Adicionar</button>
            </div>
        </form>
    </div>
</div>

// personalfinances-react/src/components/AddRevenueModal.js
import React, { useState } from 'react';


export default function AddRevenueModal({ visible, setVisible, addRevenueCallback }) {
    const [revenueTitle, setRevenueTitle] = useState("");
    const [revenueValue, setRevenueValue] = useState(0);

    function addRevenue(event) {
        event.preventDefault();

        if (!revenueValue || revenueTitle.trim() === '') {
            alert("Todos os campos são obrigatórios");
            return;
        }

        if (revenueValue < 0) {
            alert("Valor da receita inválido");
            return;
        }

        setVisible(false);
        addRevenueCallback(revenueValue);
    }

    return (
        <div id="modalAddRevenue" className="modal" style={{ display: (visible ? 'flex' : 'none') }}>
            <div className="modal-content revenue">
                <div className="modal-header">
                    <h2>Adicionar Receita</h2>
                    <span className="close" onClick={() => setVisible(false)}>&times;</span>
                </div>
                <form onSubmit={addRevenue}>
                    <div className="modal-body">
                        <div className="form-group">
                            <p>Adicione o titulo da receita</p>
                            <input 
                                type="text" 
                                id="tituloReceita" 
                                placeholder="Titulo..." 
                                value={revenueTitle}
                                onChange={(event) => setRevenueTitle(event.target.value)}
                            />
                        </div>
                        <div className="form-group">
                            <p>Adicione o valor da receita</p>
                            <input 
                                type="number" 
                                id="valorReceita" 
                                placeholder="Valor..."
                                value={revenueValue}
                                onChange={(event) => setRevenueValue(parseFloat(event.target.value))}
                            />
                        </div>
                    </div>
                    <div className="modal-footer">
                        <button className="add" id="btnAddReceita">Adicionar</button>
                    </div>
                </form>
            </div>
        </div>
    );
}
