// personalfinances-angular/src/app/header.component.ts
import {Component} from '@angular/core'

@Component({
    selector: 'header',
    template: `<div class="header"></div>`,
    styles: [`.header{
        position: absolute;
        top: 0;
        width: 100vw;
        height: 60px;
        background-color: #ffffff;
        border-bottom: 3px solid #b5b5b5;`]
  })
  export class HeaderComponent {
  }

// personalfinances-vue/src/components/Header.vue
<template>
    <div class="header"></div>
</template>

<script>
export default {
    data: function(){
        return{
            
        }
    }

}
</script>

<style escoped>

.header{
    position: absolute;
    top: 0;
    width: 100vw;
    height: 60px;
    background-color: #ffffff;
    border-bottom: 3px solid #b5b5b5;
}

</style>
