// personalfinances-svelte/src/Header.svelte

<div class="header">
    <img src="images/logo2.png" alt="logo">
</div>

<style>
    .header{
        position: fixed;
        top: 0;
        width: 100vw;
        height: 60px;
        background-color: #ffffff;
        border-bottom: 3px solid #b5b5b5;
        display: flex;
        align-items: center;
    }
    .header img {
        margin-left: 50px;
    }



</style>

// personalfinances-vue/src/components/Header.vue
<template>
    <div class="header">
        <img src="@/assets/logo2.png" alt="logo">
    </div>
</template>

<script>
export default {

}
</script>

<style escoped>

.header{
    position: fixed;
    top: 0;
    width: 100vw;
    height: 60px;
    background-color: #ffffff;
    border-bottom: 3px solid #b5b5b5;
    display: flex;
    align-items: center;
}

.header img {
    margin-left: 50px;
}

</style>
